// The plugin version.  This must match the version of the string files
VERSION(.9.1)

// Command names in dropdown box
STR(MAXRESTORE)
STR(MINIMIZE)
STR(MOVE)
STR(SIZE)
STR(TASKNEXT)
STR(TASKPREV)
STR(ACTIVATE)
STR(WAIT)

// Command descriptions
STR(MAXRESTORE_DESC)
STR(MINIMIZE_DESC)
STR(MOVE_DESC)
STR(SIZE_DESC)
STR(TASKNEXT_DESC)
STR(TASKPREV_DESC)
STR(ACTIVATE_DESC)
STR(WAIT_DESC)

// Move dialog
STR(MOVE_XPOS)
STR(MOVE_YPOS)

// Size dialog
STR(SIZE_WIDTH)
STR(SIZE_HEIGHT)

// Activate
STR(CLASS)
STR(CAPTION)
STR(PATTERN)
STR(CHECK_WAIT)
STR(TIME)